# Generated by Django 4.2.8 on 2026-04-27 19:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('is_student', models.BooleanField(default=True, verbose_name='Là Người học')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Là Người dạy')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDungCauHoi', models.TextField(verbose_name='Nội Dung Câu Hỏi')),
            ],
        ),
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDeThi', models.CharField(max_length=255, verbose_name='Tên Đề Thi')),
                ('thoiGianBatDau', models.DateTimeField(verbose_name='Thời Gian Bắt Đầu')),
                ('thoiGianKetThuc', models.DateTimeField(verbose_name='Thời Gian Kết Thúc')),
                ('thoiGianLamBai', models.IntegerField(help_text='Số phút làm bài', verbose_name='Thời Gian Làm Bài (Phút)')),
                ('soLanLamToiDa', models.IntegerField(default=1, verbose_name='Số Lần Làm Tối Đa')),
                ('matKhauDeThi', models.CharField(blank=True, help_text='Bỏ trống nếu không cần mật khẩu', max_length=50, null=True, verbose_name='Mật Khẩu Đề Thi')),
                ('choPhepXemKetQua', models.BooleanField(default=True, help_text='Cho phép sinh viên xem chi tiết đúng/sai sau khi thi', verbose_name='Cho Phép Xem Kết Quả')),
                ('trangThai', models.CharField(choices=[('BAN_NHAP', 'Bản nháp'), ('DA_CONG_BO', 'Đã công bố'), ('DANG_THI', 'Đang diễn ra'), ('KET_THUC', 'Đã kết thúc'), ('HUY', 'Đã hủy')], default='BAN_NHAP', max_length=20, verbose_name='Trạng Thái')),
                ('danhSachCauHoi', models.ManyToManyField(related_name='cac_de_thi', to='quiz.cauhoi', verbose_name='Danh Sách Câu Hỏi')),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenKhoa', models.CharField(max_length=255, unique=True, verbose_name='Tên Khoa')),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenMonHoc', models.CharField(max_length=255, verbose_name='Tên Môn Học')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_mon_hoc', to='quiz.khoa', verbose_name='Khoa')),
            ],
        ),
        migrations.CreateModel(
            name='NganHangCauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenNganHang', models.CharField(max_length=255, verbose_name='Tên Ngân Hàng')),
                ('monHoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.monhoc', verbose_name='Môn Học')),
                ('nguoiQuanLy', models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_ngan_hang_quan_ly', to=settings.AUTH_USER_MODEL, verbose_name='Người Quản Lý')),
            ],
        ),
        migrations.CreateModel(
            name='LuaChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDungLuaChon', models.TextField(verbose_name='Nội Dung Lựa Chọn')),
                ('dapAnDung', models.BooleanField(default=False, verbose_name='Đáp Án Đúng')),
                ('cauHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_lua_chon', to='quiz.cauhoi', verbose_name='Câu Hỏi')),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maLop', models.CharField(help_text='VD: INT1306_01', max_length=50, unique=True, verbose_name='Mã Lớp')),
                ('danhSachSinhVien', models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='cac_lop_dang_hoc', to=settings.AUTH_USER_MODEL, verbose_name='Danh Sách Sinh Viên')),
                ('giangVien', models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_lop_giang_day', to=settings.AUTH_USER_MODEL, verbose_name='Giảng Viên')),
                ('monHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_lop_hoc', to='quiz.monhoc', verbose_name='Môn Học')),
            ],
        ),
        migrations.CreateModel(
            name='KetQuaThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemSo', models.FloatField(blank=True, null=True, verbose_name='Điểm Số')),
                ('thoiGianBatDau', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Gian Bắt Đầu Làm')),
                ('thoiGianNopBai', models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Nộp Bài')),
                ('deThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.dethi', verbose_name='Đề Thi')),
                ('sinhVien', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh Viên')),
            ],
        ),
        migrations.AddField(
            model_name='dethi',
            name='lopHoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_de_thi', to='quiz.lophoc', verbose_name='Lớp Học'),
        ),
        migrations.AddField(
            model_name='dethi',
            name='nguoiTao',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_de_thi_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo'),
        ),
        migrations.CreateModel(
            name='ChiTietBaiLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.cauhoi', verbose_name='Câu Hỏi')),
                ('ketQua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quiz.ketquathi', verbose_name='Kết Quả Thi')),
                ('luaChonDaChon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.luachon', verbose_name='Lựa Chọn Đã Chọn')),
            ],
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='nganHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_cau_hoi', to='quiz.nganhangcauhoi', verbose_name='Ngân Hàng Câu Hỏi'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='nguoiTao',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo'),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.khoa', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
