"""
Django settings for q_test1 project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-e&j6ao360)5_70i!(m-%ry5x%+_8u7#qq6r0jsium8btv&+xtv",
)

# SECURITY WARNING: don't run with debug turned on in production!
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
DEBUG = os.getenv("DEBUG", "True" if not RENDER_EXTERNAL_HOSTNAME else "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
extra_hosts = os.getenv("ALLOWED_HOSTS")
if extra_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in extra_hosts.split(",") if h.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quiz'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'q_test.urls'

import os  # nhớ import này

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'q_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Q_TEST',             # Tên Database của bạn
        'HOST': 'localhost',          # Hoặc tên máy tính\tên instance (Ví dụ: 'localhost\\SQLEXPRESS')
        'PORT': '',                   # Có thể để trống hoặc xóa luôn dòng này
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server', # Đảm bảo đúng phiên bản driver trên máy bạn
            'extra_params': 'Trusted_Connection=yes;', # <--- ĐÂY LÀ DÒNG QUAN TRỌNG NHẤT
        },
    }
}

# Render/Linux: default to SQLite to avoid requiring SQL Server/ODBC.
# Local Windows dev: keep SQL Server, but allow overriding via env vars.
if os.name == "nt":
    DATABASES["default"]["NAME"] = os.getenv("MSSQL_NAME", DATABASES["default"].get("NAME", "Q_TEST"))
    DATABASES["default"]["HOST"] = os.getenv("MSSQL_HOST", DATABASES["default"].get("HOST", "localhost"))
    DATABASES["default"]["PORT"] = os.getenv("MSSQL_PORT", DATABASES["default"].get("PORT", ""))
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["driver"] = os.getenv(
        "MSSQL_DRIVER",
        DATABASES["default"]["OPTIONS"].get("driver", "ODBC Driver 17 for SQL Server"),
    )
    DATABASES["default"]["OPTIONS"]["extra_params"] = os.getenv(
        "MSSQL_EXTRA_PARAMS",
        DATABASES["default"]["OPTIONS"].get("extra_params", "Trusted_Connection=yes;"),
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
